/*

 PLAYBUTTON.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 22

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __playbutton_h_INCLUDE
#define __playbutton_h_INCLUDE

#include <gb/gb.h>

/* Bank of tiles. */
#define playbuttonBank 21
/* Start of tile array. */
BANKREF_EXTERN(playbutton)
extern const unsigned char playbutton[];

#endif

/* End of PLAYBUTTON.H */
